### PR TITLE
Issue13 idea directory needs to be ignored

### PR DESCRIPTION
**Pull request by yelzhanzh**

### CODE REVIEW

**Comment by spyropoulosl** [comment]
I see that you merge them yourself. That's not proper as I am not review it. The whole purpose of the pull requests are to be reviewed.

Open the pull request and I will merge them once reviewed.

**Comment by yelzhanzh** [comment]
Yeah sorry, wanted to see the changes in idea strraightaway. Will revert now

**Comment by spyropoulosl** [comment]
there's no point reverting it now. Just continue for now

**Comment by yelzhanzh** [comment]
Ok, will carry on with other issues then

**Pull request merged**
